stages:
  - deploy

deploy-job-master:
  stage: deploy
  image: docker:latest
  script:
    - docker ps
    - docker system prune -a --volumes -f
    - docker login -u pasubi -p $dockerhub
    - cd BookHub && docker buildx build --progress=plain --force-rm --push -t pasubi/bookhub24d:latest .
  environment:
    name: staging
  only:
    - main