# ---Development build---
services:
  sql:
    image: postgres:16
    container_name: bookhub-sql-dev
    ports:
      - "7890:5432"
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookhub
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: bookhub-app-dev
    working_dir: /src
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/src:cached
      - nuget_cache:/root/.nuget/packages
      - ./https:/https:ro
    command: >
      sh -c "
        dotnet restore &&
        dotnet watch run --project WebApp/WebApp.csproj --no-launch-profile --no-restore --non-interactive
      "
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=bookhub-sql-dev;Port=5432;Database=bookhub;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/bookhub.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "MyPassword"
      Smtp__Password: 'APP_PSW'
    depends_on:
      sql:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  sql-volume:
    name: bookhub-sql-data-dev
  nuget_cache:
