services:
  sql:
    image: postgres:16.4
    env_file: [.env]
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - sql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    init: true
    networks: [ bookhub-net ]

  migrator:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    working_dir: /app
    volumes:
      - ./artifacts:/app:ro
    env_file: [.env]
    depends_on:
      sql:
        condition: service_healthy
    entrypoint: ["/app/efbundle"]
    restart: "no"
    init: true
    networks: [ bookhub-net ]

  app:
    image: ghcr.io/psssart/book-hub-app:${APP_IMAGE_TAG}
    env_file: [ .env ]
    depends_on:
      sql:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,mode=1777
    volumes:
      - ./app_data_protection:/app_data_protection:rw
    environment:
      ASPNETCORE_DATA_PROTECTION_DIR: /app_data_protection
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    extra_hosts:
      - "mail.myapp.com:host-gateway"
    networks: [ bookhub-net ]

volumes:
  sql-data:
  app-dp-keys:

networks:
  bookhub-net:
    