services:
  sql:
    image: postgres:16
    container_name: nutikas2-sql
    ports:
      # external: internal
      - 7890:5432
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options: 
        max-size: 10m
        max-file: 3
        
  app:
    build: ./
    container_name: nutikas2-app
    ports:
      - 8080:8080
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3
    environment:
      ConnectionStrings__DefaultConnection: "Host=nutikas2-sql;Port=5432;Database=nutikas2;Username=postgres;Password=postgres"
    depends_on:
      - sql
        
volumes:
  sql-volume: